### ISSUE TITLE
Commit: speciální znaky

### ISSUE THREAD

**Issue by FilipChalupa** [Onset/git-latex#58]
C:\Users\Filip\Desktop\FitGit-windows-v0.0.29\FitGit-win32-ia32\resources\app.asar\components\Commi…:84 ChildProcessError: Command failed: cd C:\z\temp\444 && git add Já jsem Lůděk.txt
fatal: pathspec 'Já' did not match any files
 `cd C:\z\temp\444 && git add Já jsem Lůděk.txt` (exited with error code 128)
    at callback (C:\Users\Filip\Desktop\FitGit-windows-v0.0.29\FitGit-win32-ia32\resources\app.asar\node_modules\child-process-promise\lib\index.js:33:27)
    at ChildProcess.exithandler (child_process.js:230:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
Promise.resolve.then.catch @ C:\Users\Filip\Desktop\FitGit-windows-v0.0.29\FitGit-win32-ia32\resources\app.asar\components\Commi…:84
4C:\Users\Filip\Desktop\FitGit-windows-v0.0.29\FitGit-win32-ia32\resources\app.asar\containers\Watch…:175

**Comment by FilipChalupa** [comment]
vyřešeno
